= Walkthrough 2
© 2014 Farata Systems LLC. <training@faratasystems.com>
:icons: font
:last-update-label!:
:sectanchors:
:idprefix:
:numbered!:
:source-highlighter: highlightjs


In this walkthrough we will implement navigation between Home and Search pages _without_ using routing. We will achieve the same result as in the Homework 1, but using AngularJS-specific features.

== Steps

. Use `walkthroughs/w2` directory from the provided handouts as the starting point for the walkthrough.

. Open `scripts/app.js` file
[style="upperalpha"]
.. Define self-executable anonymous function:
+
[source,js]
----
(function () {

}());
----

.. Inside the function declare `use strict` directive:
+
[source,js]
----
(function () {
  'use strict';
}());
----

.. Right after `'use strict';` directive create new AngularJS module with name `auction`. It will be your main application module:
+
[source,js]
----
(function () {
  'use strict';

  angular.module('auction', []); <1>
}());
----
<1> Notice how we provide the second argument to the `module()` function to actually create the module, not to get an existing one.

. Open the file `scripts/controller/HomeController.js`
[style="upperalpha"]
.. Define there a self-executable anonymous function:
+
[source,js]
----
(function () {

}());
----

.. Inside the function declare `use strict` directive:
+
[source,js]
----
(function () {
  'use strict';
}());
----

.. Right after `'use strict';` directive define a constructor-function `HomeController` with a single parameter `productService`:
+
[source,js]
----
var HomeController = function (productService) {
};
----

.. Inside the constructor function save value of `this` into a local variable `_this`:
+
[source,js]
----
var HomeController = function (productService) {
  var _this = this;
};
----

.. Create a property `products` on the `_this` object. Initialize it with an empty array:
+
[source,js]
----
_this.products = [];
----

.. Invoke the `getFeaturedProducts()` method of the `productService`. Inside the `then` callback initialize the `products` property created in the previous step with the data received from the service.
+
[source,js]
----
productService.getFeaturedProducts()
    .then(function (data) { _this.products = data; });
----

.. Outside the `HomeController` constructor function, initialize the `$inject` property of the `HomeController` with an array with single dependency - `ProductService`:
+
[source,js]
----
HomeController.$inject = ['ProductService']; <1>
----
<1> `$inject` - is the way we ask AngularJS to inject registered dependencies into our constructor function.

.. Register `HomeController` inside the Angular's Dependency Injection container using the `controller()` method:
+
[source,js]
----
angular.module('auction').controller('HomeController', HomeController);
----

. Open `scripts/controller/SearchController.js`. Repeat the same steps you did for the `HomeController` to define `SearchController`, but instead of invoking `getProducts()` method (step 3F) invoke the `find()` method. Inject the `ProductService` and register the `SearchController`:
+
[source,js]
----
productService.find()
    .then(function (data) { _this.products = data; });

SearchController.$inject = ['ProductService'];
angular.module('auction').controller('SearchController', SearchController);
----


. Now you need to define a product service. Open the `scripts/service/ProductService.js` file
[style="upperalpha"]
.. Define a self-executable anonymous function:
+
[source,js]
----
(function () {

}());
----

.. Inside the function declare `use strict` directive:
+
[source,js]
----
(function () {
  'use strict';
}());
----

.. Right after the `'use strict';` directive define a constructor-function `ProductService` with a single parameter `$http`, which will perform the AJAX requests to get the JSON data:
+
[source,js]
----
var ProductService = function ($http) {
};
----

.. Create a property `$http` on the `this` object. Initialize it with `$http` service. This way you'll make it available for other `ProductService` methods:
+
[source,js]
----
var ProductService = function ($http) {
  this.$http = $http;
};
----

.. Initialize the `ProductService`'s `prototype` property with an object literal. Inside the object define two properties and initialize them with anonymous functions. This way we declare instance methods:
+
[source,js]
----
ProductService.prototype = {
  getProducts: function () {},
  find: function () {}
};
----

.. Inside the `getProducts()` curly braces use the `$http` service available as `$http` property on `this` object, to make the HTTP GET request to the static JSON file `products-featured.json`. Inside the `then()` callback unwrap products from the HTTP response object and return them:
+
[source,js]
----
getProducts: function () {
  return this.$http.get('data/products-featured.json')
      .then(function (resp) { return resp.data; });
}
----

.. Do the same thing as in the previous step for the `find()` function, but make the HTTP GET request to retrieve the data from the `products-search.json` file:
+
[source,js]
----
find: function () {
  return this.$http.get('data/products-search.json')
      .then(function (resp) { return resp.data; });
}
----

.. Initialize the `$inject` property of the `ProductService` constructor function with an array with single dependency - `$http` service:
+
[source,js]
----
ProductService.$inject = ['$http'];
----

.. Register `ProductService` inside the Angular's DI container using the `service()` method:
+
[source,js]
----
angular.module('auction').service('ProductService', ProductService);
----


. Open the `index.html` file
[style="upperalpha"]
.. Bootstrap AngularJS application using `ng-app` directive with the module name:
+
[source,html]
----
<html ng-app="auction"> <1>
----
<1> Notice how we initialize the `ng-app` directive with the `auction` value. It *must* be the same as the name you use to create main application module.

.. Using `ng-init` directive create a new variable `currentView` on the root scope and initialize it with `'home'`:
+
[source,html]
----
<div class="row" ng-init="currentView = 'home'"> <1>
----
<1> `ng-init` is not a best practice, use it only for quick prototyping.

.. Using the `ng-include` directive, specify the path to the currently displayed view for the `div`. Inside the expression use the `currentView` variable to always show the actual page:
+
[source,html]
----
<div class="row" ng-init="currentView = 'home'" ng-include="'views/' + currentView + '.html'">
----

.. Add the navigation to the Home page, by defining `ng-click` directive for the brand name link:
+
[source,html]
----
<a class="navbar-brand" ng-click="currentView = 'home'">ABC Auction</a>
----

.. Add navigation to the Search page, by using the `ng-click` directive for the Search button:
+
[source,html]
----
<a ng-click="currentView = 'search'" class="btn btn-default">Search</a>
----

. Open the file `veiws/home.html`
[style="upperalpha"]
.. Define the `ng-controller` directive for the top level <div>. Assign the `HomeController` to this <div>:
+
[source,html]
----
<div ng-controller="HomeController as ctrl"> <1>
----
<1> Notice how we use _controller as_ feature to expose all controller's instance fields and methods on the scope via the name `ctrl`.

.. Using `ng-repeat` iterate through the products available on the `ctrl` object:
+
[source,html]
----
<li class="col-md-4" ng-repeat="product in ctrl.products"> <1>
----
<1> `ng-repeat` creates a new _child scope_, so within the `ng-repeat` directive you can use the `product` variable to reference the current product.

.. Using `ng-src` directive define the path to the current product's thumbnail:
+
[source,html]
----
<img ng-src="images/{{ product.thumb }}" alt="" class="img-responsive"> <1>
----
<1> Unlike the HTML attribute `src`, the `ng-src` prevents making HTTP request till the data-binding expression is resolved.

.. Using the data-binding expressions display the title and description of the current product:
+
[source,html]
----
<h2><a>{{ product.title }}</a></h2>
<p>{{ product.description }}</p>
----

. Open the file `views/search.html`
[style="upperalpha"]
.. Define the `ng-controller` directive for the top level div. Initialize it with `SearchController`:
+
[source,html]
----
<div ng-controller="SearchController as ctrl">
----

.. Using `ng-repeat` iterate through the products available on the `ctrl`:
+
[source,html]
----
<li class="col-md-4" ng-repeat="product in ctrl.products">
----

.. Using the `ng-src` directive define the path to the current product's thumbnail:
+
[source,html]
----
<img ng-src="images/{{ product.thumb }}" alt="" class="img-responsive">
----

.. Using the data-binding expressions display the title and description of the current product:
+
[source,html]
----
<h2><a>{{ product.title }}</a></h2>
<p>{{ product.description }}</p>
----

.. Using the data-binding expressions display the auction time left, the watchers and price of the current product:
+
[source,html]
----
<span class="badge">{{ product.timeleft }} hour left</span>
----
+
[source,html]
----
<span class="badge">
  <span class="glyphicon glyphicon-eye-open"></span> {{ product.watchers }}
</span>
----
+
[source,html]
----
<span class="badge">
  {{ product.price | currency }} <1>
</span>
----
<1> Notice how we use the Angular's built-in `currency` filter to represent the price in a human-readable way.
